### ISSUE TITLE
A.1.1 Authorised Requester 

### ISSUE THREAD

**Issue by chuiheng-wu** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#1]
As a risk manager, I want to authorise the identification of the requester, so that I can ensure valid enquiry is processed securely.

**Comment by ChrisZZY** [comment]
**Acceptance Criteria**: the product can authorise users whose identifications are valid.

**Comment by chuiheng-wu** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
