### ISSUE TITLE
A.1.3 Collect Requested Details 

### ISSUE THREAD

**Issue by ChrisZZY** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#10]
As a project manager, I want to record all necessary information in inquiry, so that I can process the request more effectively

**Comment by ChrisZZY** [comment]
**Acceptance Criteria:** the server can collect and record all the necessary information in the request form, and it can be safely stored in the database.

**Comment by chuiheng-wu** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
