### ISSUE TITLE
A.1.4 Collect Special Needs 

### ISSUE THREAD

**Issue by ChrisZZY** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#11]
As a project manager, I want to record any special needs that the customer has, so that the service required can be conducted with a more comprehensive understanding

**Comment by ChrisZZY** [comment]
**Acceptance Criteria:** The server can accept any special need as additional information in a string form.

**Comment by chuiheng-wu** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
