### ISSUE TITLE
B.1.2 Send verification request to university

### ISSUE THREAD

**Issue by chuiheng-wu** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#15]

**Comment by chuiheng-wu** [comment]
**Acceptance Criteria:** Once sending the verification request is sent, the corresponding university will receive an email with a verification link that they can click for confirmation.

**Comment by JeremiahXing** [comment]
Final Review: 
**UI/UX check**: pass
**Code quality check**: pass
