### ISSUE TITLE
C.3.1 Set up digital wallet

### ISSUE THREAD

**Issue by chuiheng-wu** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#17]

**Comment by chuiheng-wu** [comment]
**Acceptance Criteria:** Users are able to choose eoa (i.e., needs blockchain knowledge to interact without password recovery) or ca (same as account signup/in on normal shopping website with password recovery) to connect their crypto wallets for further minting to be processed.

**Comment by chuiheng-wu** [comment]
**Feasibility check**: pass / not pass  
**UI/UX check**: pass / not pass 
**Code quality check**: pass / not pass

**Comment by JeremiahXing** [comment]
Feasibility check: pass 
UI/UX check: pass 
Code quality check: pass
