### ISSUE TITLE
D.1.1 Verify user's identity

### ISSUE THREAD

**Issue by chuiheng-wu** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#18]

**Comment by chuiheng-wu** [comment]
Acceptance Criteria Wallet ensures only the account owner can connect to the system, which needs an email account and password (even a verification code using ERC4337 excluding Gmail or apple users.)

**Comment by JeremiahXing** [comment]
Feasibility check: pass 
UI/UX check: pass
Code quality check: pass
