### ISSUE TITLE
A.1.5 Present Subscription Plans

### ISSUE THREAD

**Issue by MingdaSong** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#20]

**Comment by MingdaSong** [comment]
Finished present subscription plans

**Comment by MingdaSong** [comment]
Acceptance criteria for A.1.5 Present Subscription Plans:

- The system should display the available subscription plans in a clear and organized manner
- The subscription plans should include details such as pricing, duration, and included features

**Comment by ChrisZZY** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
