### ISSUE TITLE
A.1.6 Personalized Quotes

### ISSUE THREAD

**Issue by MingdaSong** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#21]

**Comment by MingdaSong** [comment]
Finished customizable subscription plans for issuing organisations

**Comment by MingdaSong** [comment]
Acceptance Criteria:

- The system shall provide a feature for creating personalized subscription plans.

**Comment by ChrisZZY** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
