### ISSUE TITLE
C.3.7 Allow web-based acess 

### ISSUE THREAD

**Issue by MingdaSong** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#25]

**Comment by MingdaSong** [comment]
Finished web-based platform

**Comment by MingdaSong** [comment]
Acceptance Criteria:

- The web-based platform should be accessible through standard web browsers such as Google Chrome, Mozilla Firefox, and Safari.
- The platform should have a user-friendly and intuitive interface that enables users to easily navigate and interact with the system.
- The platform should be optimized for different screen sizes and resolutions, including desktops, laptops, tablets, and mobile devices.

**Comment by ChrisZZY** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
