### ISSUE TITLE
D.2.2 Store the user's account information

### ISSUE THREAD

**Issue by MingdaSong** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#27]

**Comment by MingdaSong** [comment]
Acceptance Criteria:
- User account information should be stored securely and encrypted in the database.
- The database should have a table named 'user_account' with columns for storing user information such as username, password, email, etc.
- User account information should be accessible only with the user's permission and appropriate authentication measures should be in place.
- The database should allow for easy retrieval of user account information using appropriate SQL queries.
- The user account information should be backed up regularly to prevent data loss in case of system failure.
- The database should comply with relevant data protection regulations and standards.

**Comment by ChrisZZY** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
