### ISSUE TITLE
D.3.1 Generate & valid user account

### ISSUE THREAD

**Issue by MingdaSong** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#29]

**Comment by MingdaSong** [comment]
Acceptance Criteria:

- User account can be generated with minimal user input
- User account includes a unique username and password
- User account information is stored securely and can be accessed by authorized personnel only

**Comment by ChrisZZY** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
