### ISSUE TITLE
B.3.1 Non-transferable NFT bind with user's account address

### ISSUE THREAD

**Issue by kylifish0100** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#38]

**Comment by kylifish0100** [comment]
**Acceptance Criteria**: NFT is not able to be transferred to other address. Error notification will be displayed when user trying to transfer.

**Comment by NormanZhang-zzt** [comment]
Final Review: 
**UI/UX check**: pass
**Code quality check**: pass
