### ISSUE TITLE
C.3.2 Request to generate new NFT

### ISSUE THREAD

**Issue by JeremiahXing** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#40]
As a **user**,

I want to generate my own qualifications NFT without blockchain knowledge,

so that I can use my qualification NFT quickly.

**Comment by JeremiahXing** [comment]
Acceptance Criteria: user can send request to generate NFT.

**Comment by kylifish0100** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
