### ISSUE TITLE
C.3.3 Add NFT

### ISSUE THREAD

**Issue by JeremiahXing** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#41]
As a **user**, 

I want to hold more than one qualification NFT

so that I can show my whole academic history

**Comment by JeremiahXing** [comment]
Acceptance Criteria: The user can generate more than one NFT.

**Comment by kylifish0100** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
