### ISSUE TITLE
B.4.2 Users can check their own and others NFT

### ISSUE THREAD

**Issue by JeremiahXing** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#44]
As an NFT manager, 

I want to limit the NFT to have one official owner, 

so that others cannot modify and duplicate a new NFT qualification.

**Comment by JeremiahXing** [comment]
**Acceptance criteria**: Users can check the transaction via checking the links and view them in blockchain explorers like etherscan.

**Comment by kylifish0100** [comment]
Final Review: 
**UI/UX check**: pass
**Code quality check**: pass
