### ISSUE TITLE
F.1.2 Off-chain storge

### ISSUE THREAD

**Issue by JeremiahXing** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#45]
As a system architect,

I want to store data off the blockchain, 

so that the problem of slow access to the main chain is solved.

**Comment by JeremiahXing** [comment]
Acceptance Criteria: User can successfully upload their metadata to IPFS decentralized storage before mint new certification on chain.

**Comment by kylifish0100** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
