### ISSUE TITLE
D.2.1 Verify the user's information 

### ISSUE THREAD

**Issue by MingdaSong** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#6]

**Comment by ChrisZZY** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass

**Comment by MingdaSong** [comment]
The system shall check whether the user's email address and phone number are unique and have not been used before for registration.
The system shall prompt the user to enter valid and complete information in case any mandatory fields are left blank or contain invalid characters.

**Comment by ChrisZZY** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
