### ISSUE TITLE
A.1.2 Check Requester

### ISSUE THREAD

**Issue by ChrisZZY** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#9]
As a project manager, I want to check the reqeuster is authorised, so that only authorised people can request NFT

**Comment by ChrisZZY** [comment]
**Acceptance Criteria**: the server is able to check if the authorised, and only authorised people can make requests.

**Comment by chuiheng-wu** [comment]
Feasibility check: pass
UI/UX check: pass
Code quality check: pass
